processing:
  target: freework
  outputs:
    villeideal:
      type: bigquery
      method: oauth
      project: dev-env-368414
      dataset: villeideal
      threads: 4
      timeout_seconds: 300
      location: europe-west1
      priority: interactive
      retries: 1

    freework:
      type: bigquery
      method: oauth
      project: dev-env-368414
      dataset: freework
      threads: 4
      timeout_seconds: 300
      location: europe-west1
      priority: interactive
      retries: 1

    freelance_info:
      type: bigquery
      method: oauth
      project: dev-env-368414
      dataset: freelance_info
      threads: 4
      timeout_seconds: 300
      location: europe-west1
      priority: interactive
      retries: 1


    danem_people:
      type: bigquery
      method: oauth
      project: dev-env-368414
      dataset: danem_people
      threads: 4
      timeout_seconds: 300
      location: europe-west1
      priority: interactive
      retries: 1
