processing:
  target: freework
  outputs:
    villeideal:
      type: bigquery
      method: oauth
      project: "{{env_var('GCP_PROJECT_ID','dev-env-368414')}}"
      dataset:  "{{env_var('BQ_DATASET','villeideal')}}"
      threads: 4
      timeout_seconds: 300
      location: "{{env_var('BQ_REGION','europe-west1')}}"
      priority: interactive
      retries: 1

    freework:
      type: bigquery
      method: oauth
      project: "{{env_var('GCP_PROJECT_ID','dev-env-368414')}}"
      dataset: "{{env_var('BQ_DATASET','freework')}}" 
      threads: 4
      timeout_seconds: 300
      location: "{{env_var('BQ_REGION','europe-west1')}}"
      priority: interactive
      retries: 1

    freelance_info:
      type: bigquery
      method: oauth
      project: "{{env_var('GCP_PROJECT_ID','dev-env-368414')}}"
      dataset: "{{env_var('BQ_DATASET','freelance_info')}}"
      threads: 4
      timeout_seconds: 300
      location: "{{env_var('BQ_REGION','europe-west1')}}"
      priority: interactive
      retries: 1


    danem_people:
      type: bigquery
      method: oauth
      project: "{{env_var('GCP_PROJECT_ID','dev-env-368414')}}"
      dataset: "{{env_var('BQ_DATASET','danem_people')}}"
      threads: 4
      timeout_seconds: 300
      location: "{{env_var('BQ_REGION','europe-west1')}}"
      priority: interactive
      retries: 1
