stages:
  - validate
  - authenticate
  - build

variables:
  GCP_PROJECT_ID: "dev-env-368414"
  GCP_PROJECT_NUMBER: "932412034179"

  WIF_POOL_ID: "airflowpool"
  WIF_PROVIDER_ID: "gitlab-provider"

  GCP_SERVICE_ACCOUNT: "gitlab-ci@dev-env-368414.iam.gserviceaccount.com"

  GOOGLE_APPLICATION_CREDENTIALS: "$CI_PROJECT_DIR/.gcp-wif-credentials.json"
  GITLAB_OIDC_TOKEN_FILE: "$CI_PROJECT_DIR/.gitlab-oidc-token"

  IMAGE_TAG: "$CI_COMMIT_SHORT_SHA"


# Template réutilisable pour tous les jobs qui accèdent à GCP
.gcp_wif_authentication:
  image: google/cloud-sdk:latest

  id_tokens:
    GITLAB_OIDC_TOKEN:
      aud: "https://iam.googleapis.com/projects/932412034179/locations/global/workloadIdentityPools/airflowpool/providers/gitlab-provider"

  before_script:
    # Enregistre temporairement le token OIDC fourni par GitLab
    - printf '%s' "$GITLAB_OIDC_TOKEN" > "$GITLAB_OIDC_TOKEN_FILE"

    # Génère la configuration WIF
    - >
      gcloud iam workload-identity-pools create-cred-config
      "projects/${GCP_PROJECT_NUMBER}/locations/global/workloadIdentityPools/${WIF_POOL_ID}/providers/${WIF_PROVIDER_ID}"
      --service-account="${GCP_SERVICE_ACCOUNT}"
      --credential-source-file="${GITLAB_OIDC_TOKEN_FILE}"
      --output-file="${GOOGLE_APPLICATION_CREDENTIALS}"

    # Authentifie gcloud avec WIF
    - >
      gcloud auth login
      --cred-file="${GOOGLE_APPLICATION_CREDENTIALS}"
      --quiet

    # Configure le projet GCP
    - gcloud config set project "$GCP_PROJECT_ID"

  after_script:
    # Supprime les fichiers d’authentification temporaires
    - rm -f "$GITLAB_OIDC_TOKEN_FILE"
    - rm -f "$GOOGLE_APPLICATION_CREDENTIALS"


# Étape 1 : validation des fichiers
validate_configuration:
  stage: validate
  image: alpine:latest

  script:
    - test -f cloudbuild.yaml
    - test -f dockerfile
    - echo "Les fichiers requis sont présents."
    - echo "IMAGE_TAG=${IMAGE_TAG}"

  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'


# Étape 2 : vérification de l’authentification GCP
authenticate_gcp:
  stage: authenticate
  extends: .gcp_wif_authentication

  script:
    - echo "Vérification de l’identité GCP active..."
    - gcloud auth list
    - gcloud auth print-access-token > /dev/null
    - echo "Authentification WIF et impersonation réussies."

  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'


# Étape 3 : déclenchement du Cloud Build pour l'image
submit_cloud_build:
  stage: build
  extends: .gcp_wif_authentication

  script:
    - echo "Soumission du build avec IMAGE_TAG=${IMAGE_TAG}"

    - >
      gcloud builds submit
      --project="${GCP_PROJECT_ID}"
      --config="cloudbuild.yaml"
      --substitutions="_PROJECT_ID=${GCP_PROJECT_ID},_IMAGE_TAG=${IMAGE_TAG}"
      .

  rules:
  - if: '$CI_COMMIT_BRANCH == "main"'
    changes:
      - dockerfile
      - requirements.txt
      - docker-compose.yml
      - cloudbuild.yaml
      - dbt/**/*
      - entrypoint.sh
      - wait-for-it.sh


# Étape 3 : déclenchement du Cloud Build pour dag
submit_dag_cloud_build:
  stage: build
  extends: .gcp_wif_authentication

  script:
    - echo "Soumission du dag build avec TAG=${IMAGE_TAG}"

    - >
      gcloud builds submit
      --project="${GCP_PROJECT_ID}"
      --config="cloudbuild-dags.yaml"
      --substitutions="_PROJECT_ID=${GCP_PROJECT_ID}"
      .

  rules:
  - if: '$CI_COMMIT_BRANCH == "main"'
    changes:
      - dags/**/*
      - cloudbuild-dags.yaml
