version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-airflow}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-change-me-postgres-password}
      POSTGRES_DB: ${POSTGRES_DB:-airflow}

    networks:
      - airflow-network
    volumes:
      - airflow_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    restart: unless-stopped

  redis:
    image: redis:latest
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 50
    networks:
      - airflow-network


  airflow-init:
    image: europe-west1-docker.pkg.dev/${PROJECT_ID}/airflow/airflow:${IMAGE_TAG}
    container_name: airflow-init
    command: >
      bash -c "
      mkdir -p /opt/airflow/logs &&
      airflow db init &&
      airflow users create --username ${AIRFLOW_ADMIN_USERNAME:-admin} --firstname ${AIRFLOW_ADMIN_FIRSTNAME:-Admin} --lastname ${AIRFLOW_ADMIN_LASTNAME:-User} --role Admin --email ${AIRFLOW_ADMIN_EMAIL:-admin@example.com} --password ${AIRFLOW_ADMIN_PASSWORD:-change-me-airflow-admin-password}
      "
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER:-airflow}:${POSTGRES_PASSWORD:-change-me-postgres-password}@postgres:5432/${POSTGRES_DB:-airflow}
      - AIRFLOW_ADMIN_USERNAME
      - AIRFLOW_ADMIN_FIRSTNAME
      - AIRFLOW_ADMIN_LASTNAME
      - AIRFLOW_ADMIN_EMAIL
      - AIRFLOW_ADMIN_PASSWORD
      - GOOGLE_APPLICATION_CREDENTIALS_JSON
      - AIRFLOW_CONN_GOOGLE_CLOUD_DEFAULT
    user: root
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - airflow-network

  airflow-webserver:
    image: europe-west1-docker.pkg.dev/${PROJECT_ID}/airflow/airflow:${IMAGE_TAG}
    container_name: airflow-webserver
    command: airflow webserver
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER:-airflow}:${POSTGRES_PASSWORD:-change-me-postgres-password}@postgres:5432/${POSTGRES_DB:-airflow}
      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0
      - AIRFLOW__CELERY__RESULT_BACKEND=redis://redis:6379/0
      - AIRFLOW__CORE__REMOTE_LOGGING=True
      - AIRFLOW__LOGGING__REMOTE_LOGGING=True
      - AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER=gs://${GCS_LOGGING_BUCKET}
      - AIRFLOW__LOGGING__REMOTE_LOG_CONN_ID=google_cloud_default
      - AIRFLOW__API__AUTH_BACKENDS=airflow.api.auth.backend.basic_auth
      - AIRFLOW_CONN_SLACK_WEBHOOK
      - AIRFLOW_ADMIN_USERNAME
      - AIRFLOW_ADMIN_FIRSTNAME
      - AIRFLOW_ADMIN_LASTNAME
      - AIRFLOW_ADMIN_EMAIL
      - AIRFLOW_ADMIN_PASSWORD
      - GOOGLE_APPLICATION_CREDENTIALS_JSON
      - AIRFLOW_CONN_GOOGLE_CLOUD_DEFAULT
    ports:
      - "8080:8080"
    networks:
      - airflow-network
    depends_on:
      airflow-init:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  airflow-scheduler:
    image: europe-west1-docker.pkg.dev/${PROJECT_ID}/airflow/airflow:${IMAGE_TAG}
    container_name: airflow-scheduler
    command: airflow scheduler
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER:-airflow}:${POSTGRES_PASSWORD:-change-me-postgres-password}@postgres:5432/${POSTGRES_DB:-airflow}
      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0
      - AIRFLOW__CELERY__RESULT_BACKEND=redis://redis:6379/0
      - AIRFLOW__CORE__REMOTE_LOGGING=True
      - AIRFLOW__LOGGING__REMOTE_LOGGING=True
      - AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER=gs://${GCS_LOGGING_BUCKET}
      - AIRFLOW__LOGGING__REMOTE_LOG_CONN_ID=google_cloud_default
      - AIRFLOW__API__AUTH_BACKENDS=airflow.api.auth.backend.basic_auth
      - AIRFLOW_CONN_SLACK_WEBHOOK
      - AIRFLOW_ADMIN_USERNAME
      - AIRFLOW_ADMIN_FIRSTNAME
      - AIRFLOW_ADMIN_LASTNAME
      - AIRFLOW_ADMIN_EMAIL
      - AIRFLOW_ADMIN_PASSWORD
      - GOOGLE_APPLICATION_CREDENTIALS_JSON
      - AIRFLOW_CONN_GOOGLE_CLOUD_DEFAULT
    networks:
      - airflow-network
    depends_on:
      airflow-init:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: on-failure

  airflow-worker:
    image: europe-west1-docker.pkg.dev/${PROJECT_ID}/airflow/airflow:${IMAGE_TAG}
    container_name: airflow-worker
    command: airflow celery worker
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER:-airflow}:${POSTGRES_PASSWORD:-change-me-postgres-password}@postgres:5432/${POSTGRES_DB:-airflow}
      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0
      - AIRFLOW__CELERY__RESULT_BACKEND=redis://redis:6379/0
      - AIRFLOW__CORE__REMOTE_LOGGING=True
      - AIRFLOW__LOGGING__REMOTE_LOGGING=True
      - AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER=gs://${GCS_LOGGING_BUCKET}
      - AIRFLOW__LOGGING__REMOTE_LOG_CONN_ID=google_cloud_default
      - AIRFLOW__API__AUTH_BACKENDS=airflow.api.auth.backend.basic_auth
      - AIRFLOW_CONN_SLACK_WEBHOOK
      - AIRFLOW_ADMIN_USERNAME
      - AIRFLOW_ADMIN_FIRSTNAME
      - AIRFLOW_ADMIN_LASTNAME
      - AIRFLOW_ADMIN_EMAIL
      - AIRFLOW_ADMIN_PASSWORD
      - GOOGLE_APPLICATION_CREDENTIALS_JSON
      - AIRFLOW_CONN_GOOGLE_CLOUD_DEFAULT
    networks:
      - airflow-network
    depends_on:
      airflow-init:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: on-failure

networks:
  airflow-network:
    driver: bridge

volumes:
  airflow_postgres_data:
    name: airflow_postgres_data
